### ISSUE TITLE
Conflict in .index folder access when multiple instances of EODAG are running in parallel

### ISSUE THREAD

**Issue by koleckt** [CS-SI/eodag#1004]
**Describe the bug**
When running multiple EODAG with the same user account, it can appear a conflict to access to the .index directory.

**Output**

This this the traceback of the error, when running 10 processes while EODAG, from the same user account
````
Traceback (most recent call last):
  File "/work/scratch/env/koleckt/.conda/envs/s1tiling-copdem/bin/S1Processor", line 33, in <module>
    sys.exit(load_entry_point('S1Tiling', 'console_scripts', 'S1Processor')())
  File "/work/scratch/env/koleckt/.conda/envs/s1tiling-copdem/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/work/scratch/env/koleckt/.conda/envs/s1tiling-copdem/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/work/scratch/env/koleckt/.conda/envs/s1tiling-copdem/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work/scratch/env/koleckt/.conda/envs/s1tiling-copdem/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/il/koleckt/s1tiling-copdem/s1tiling/s1tiling/S1Processor.py", line 144, in run
    cli_execute(s1_process, config_filename,
  File "/home/il/koleckt/s1tiling-copdem/s1tiling/s1tiling/S1Processor.py", line 75, in cli_execute
    situation = processing(*args, **kwargs)
  File "/home/il/koleckt/s1tiling-copdem/s1tiling/s1tiling/libs/api.py", line 601, in s1_process
    return do_process_with_pipeline(config_opt, builder,
  File "/home/il/koleckt/s1tiling-copdem/s1tiling/s1tiling/libs/api.py", line 369, in do_process_with_pipeline
    with S1FileManager(config) as s1_file_manager:
  File "/home/il/koleckt/s1tiling-copdem/s1tiling/s1tiling/libs/S1FileManager.py", line 505, in __init__
    self._dag = EODataAccessGateway(self.cfg.eodag_config)
  File "/work/scratch/env/koleckt/.conda/envs/s1tiling-copdem/lib/python3.8/site-packages/eodag/api/core.py", line 145, in __init__
    self.build_index()
  File "/work/scratch/env/koleckt/.conda/envs/s1tiling-copdem/lib/python3.8/site-packages/eodag/api/core.py", line 217, in build_index
    shutil.rmtree(index_dir)
  File "/work/scratch/env/koleckt/.conda/envs/s1tiling-copdem/lib/python3.8/shutil.py", line 719, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/work/scratch/env/koleckt/.conda/envs/s1tiling-copdem/lib/python3.8/shutil.py", line 717, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/il/koleckt/.config/eodag/.index'
````

**Environment:**
 - Python version: `3.8.5`
 - EODAG version: `eodag 2.10`

**Additional context**

The conf_dir is hard coded (line 121 in api/core.py )

        self.conf_dir = os.path.join(os.path.expanduser("~"), ".config", "eodag")

so all EODAG processes use the same config directory

It results that writing/reading/removing files in the .index folder is not resilient to parallel execution of EODAG processes.
 
````
    def build_index(self) -> None:
        """Build a `Whoosh <https://whoosh.readthedocs.io/en/latest/index.html>`_
        index for product types searches.
        """
        index_dir = os.path.join(self.conf_dir, ".index")

        try:
            create_index = not exists_in(index_dir)
        except ValueError as ve:
            # Whoosh uses pickle internally. New versions of Python sometimes introduce
            # a new pickle protocol (e.g. 3.4 -> 4, 3.8 -> 5), the new version not
            # being supported by previous versions of Python (e.g. Python 3.7 doesn't
            # support Protocol 5). In that case, we need to recreate the .index.
            if "unsupported pickle protocol" in str(ve):
                logger.debug("Need to recreate whoosh .index: '%s'", ve)
                create_index = True
                shutil.rmtree(index_dir)
            # Unexpected error
            else:
                logger.error(
                    "Error while opening .index using whoosh, "
                    "please report this issue and try to delete '%s' manually",
                    index_dir,
                )
                raise
````

**Comment by sbrunato** [comment]
with #927, you can now customize eodag configuration directory (which contains `.index`) with the environment variable `EODAG_CFG_DIR`. That can help avoiding the issue you had
