### ISSUE TITLE
Provider Theia

### ISSUE THREAD

**Issue by mamad223** [CS-SI/eodag#1089]
Hello,
I would like to download Sentinel-2 A data from the provider THEIA. My download process stop ramdomly with this kind of message "eodag.utils.exceptions.AuthenticationError: HTTP Error 403 returned, {"ErrorMessage":"User profile has not been validated. Please contact an administrator","ErrorCode":403}
Please check your credentials for theia" and don't know why.

**Code To Reproduce**

```sh
search_results = dag.deserialize_and_register("../S2_download/search_results.geojson")
print(f"This SearchResult stores {len(search_results)} {search_results[0].product_type} products.")
setup_logging(2)
workspace=dag.download_all(search_results)

**Output**
Traceback (most recent call last):
  File "/home/mdiarra/Workspace/script_python/telechargement_s2_eodag_theia_modif.py", line 86, in <module>
    workspace=dag.download_all(search_results)
  File "/home/mdiarra/miniconda3/envs/eodag_env/lib/python3.10/site-packages/eodag/api/core.py", line 1623, in download_all
    paths = download_plugin.download_all(
  File "/home/mdiarra/miniconda3/envs/eodag_env/lib/python3.10/site-packages/eodag/plugins/download/http.py", line 994, in download_all
    return super(HTTPDownload, self).download_all(
  File "/home/mdiarra/miniconda3/envs/eodag_env/lib/python3.10/site-packages/eodag/plugins/download/base.py", line 488, in download_all
    product.download(
  File "/home/mdiarra/miniconda3/envs/eodag_env/lib/python3.10/site-packages/eodag/api/product/_product.py", line 330, in download
    fs_path = self.downloader.download(
  File "/home/mdiarra/miniconda3/envs/eodag_env/lib/python3.10/site-packages/eodag/plugins/download/http.py", line 407, in download
    download_request(product, auth, progress_callback, wait, timeout, **kwargs)
  File "/home/mdiarra/miniconda3/envs/eodag_env/lib/python3.10/site-packages/eodag/plugins/download/base.py", line 596, in download_and_retry
    return download(*args, **kwargs)
  File "/home/mdiarra/miniconda3/envs/eodag_env/lib/python3.10/site-packages/eodag/plugins/download/http.py", line 404, in download_request
    for chunk in chunks:
  File "/home/mdiarra/miniconda3/envs/eodag_env/lib/python3.10/site-packages/eodag/plugins/download/http.py", line 634, in _stream_download
    self._process_exception(e, product, ordered_message)
  File "/home/mdiarra/miniconda3/envs/eodag_env/lib/python3.10/site-packages/eodag/plugins/download/http.py", line 521, in _process_exception
    raise AuthenticationError(
eodag.utils.exceptions.AuthenticationError: HTTP Error 403 returned, {"ErrorMessage":"User profile has not been validated. Please contact an administrator","ErrorCode":403}
Please check your credentials for theia

**Environment:**
 - Python version: `python --3.10.6`
 - EODAG version: `eodag version 2.11.0b1`

**Additional context**
I would like to download 5 tiles of S2 data with theia format.

Thank you for your help

**Comment by sbrunato** [comment]
related to #1123

**Comment by sbrunato** [comment]
This issue was caused by a bad missing-key handling in `TokenAuth` plugin. This was fixed by https://github.com/CS-SI/eodag/pull/1034.
It is not available for the moment in a stable release, but you can already use it with
```
pip install git+https://github.com/CS-SI/eodag.git@develop
```
or wait that incoming `eodag v3.0b1` is released
