### ISSUE TITLE
issue in download landsat 9 from usgs

### ISSUE THREAD

**Issue by Squiccio** [CS-SI/eodag#1233]
Using the CLI, i succesfully search for Landsat9 products but when i try to download them an error occurs

the command line:
```sh
eodag -vvv download --conf h:\eodag\LANDSAT_C2L2\LANDSAT_C2L2_config.yml --search-results h:\eodag\LANDSAT_C2L2\LANDSAT_C2L2.geojson
```
Output:
```
2024-06-21 18:19:10,556 eodag.core                       [INFO    ] (tid=29152) Downloading 3 products
Downloaded products:   0%|                                   2024-06-21 18:19:10,560 eodag.download.base              [WARNING ] (tid=29152) A problem occurred during download of product: EOProduct(id=LC09_L2SP_196027_20240618_20240619_02_T1, provider=usgs). Skipping it
2024-06-21 18:19:10,562 eodag.download.base              [DEBUG   ] (tid=29152)
Traceback (most recent call last):
  File "H:\Anaconda3\envs\Eodag\lib\site-packages\eodag\plugins\download\base.py", line 520, in download_all
    product.download(
  File "H:\Anaconda3\envs\Eodag\lib\site-packages\eodag\api\product\_product.py", line 365, in download
    fs_path = self.downloader.download(
  File "H:\Anaconda3\envs\Eodag\lib\site-packages\eodag\plugins\apis\usgs.py", line 249, in download
    self.config.products.get(  # type: ignore
AttributeError: 'PluginConfig' object has no attribute 'products'
```

**Comment by sbrunato** [comment]
Hello @Squiccio , and many thanks for submitting this issue. We'll post a fix soon
