### ISSUE TITLE
python-dateutil version conflict

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#141]
A fresh install in dev mode using `python -m pip install -r requirements-dev.txt` outputs the following error:
```sh
ERROR: pandas 1.1.0 has requirement python-dateutil>=2.7.3, but you'll have python-dateutil 2.6.1 which is incompatible.
```
And also:
```py
from eodag import EODataAccessGateway
dag = EODataAccessGateway()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sylvain/workspace/eodag-20200804/eodag/api/core.py", line 92, in __init__
    self._plugins_manager = PluginManager(self.providers_config)
  File "/home/sylvain/workspace/eodag-20200804/eodag/plugins/manager.py", line 71, in __init__
    entry_point.load()
  File "/home/sylvain/.virtualenvs/eodag-20200804/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/home/sylvain/.virtualenvs/eodag-20200804/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/sylvain/.virtualenvs/eodag-20200804/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.6.1 (/home/sylvain/.virtualenvs/eodag-20200804/lib/python3.8/site-packages), Requirement.parse('python-dateutil>=2.7.3'), {'pandas'})
```

**Comment by sbrunato** [comment]
using `pandas==1.0.5` instead of `pandas==1.1.0` is ok
