### ISSUE TITLE
Import error with rasterio 1.2.0

### ISSUE THREAD

**Issue by ctriquet-cs** [CS-SI/eodag#150]
**Describe the bug**
Since the v1.2.0 release of rasterio on 01/25/2021, importing eodag returns an error.

**Code To Reproduce**

```py
import eodag
```

**Output**

```py
/usr/local/lib/python3.6/dist-packages/geopandas/_compat.py:88: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.9.0-CAPI-1.16.2). Conversions between both will be slow.
  shapely_geos_version, geos_capi_version_string
2021-01-25 18:15:11.505651: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
...
ERROR 1: PROJ: proj_create_from_database: /usr/share/proj/proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/eodag/api/product/__init__.py", line 20, in <module>
    from eodag_cube.api.product import EOProduct  # noqa
ModuleNotFoundError: No module named 'eodag_cube'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rasterio/_crs.pyx", line 285, in rasterio._crs._CRS.from_epsg
  File "rasterio/_err.pyx", line 192, in rasterio._err.exc_wrap_int
rasterio._err.CPLE_AppDefinedError: PROJ: proj_create_from_database: /usr/share/proj/proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
    import eodag
  File "/usr/local/lib/python3.6/dist-packages/eodag/__init__.py", line 27, in <module>
    from .api.core import EODataAccessGateway  # noqa
  File "/usr/local/lib/python3.6/dist-packages/eodag/api/core.py", line 31, in <module>
    from eodag.api.search_result import SearchResult
  File "/usr/local/lib/python3.6/dist-packages/eodag/api/search_result.py", line 20, in <module>
    from eodag.api.product import EOProduct
  File "/usr/local/lib/python3.6/dist-packages/eodag/api/product/__init__.py", line 22, in <module>
    from ._product import EOProduct  # noqa
  File "/usr/local/lib/python3.6/dist-packages/eodag/api/product/_product.py", line 27, in <module>
    from eodag.api.product.metadata_mapping import NOT_AVAILABLE, NOT_MAPPED
  File "/usr/local/lib/python3.6/dist-packages/eodag/api/product/metadata_mapping.py", line 28, in <module>
    from eodag.utils import get_timestamp
  File "/usr/local/lib/python3.6/dist-packages/eodag/utils/__init__.py", line 62, in <module>
    DEFAULT_PROJ = CRS.from_epsg(4326)
  File "/usr/local/lib/python3.6/dist-packages/rasterio/crs.py", line 333, in from_epsg
    obj._crs = _CRS.from_epsg(code)
  File "rasterio/_crs.pyx", line 287, in rasterio._crs._CRS.from_epsg
rasterio.errors.CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: /usr/share/proj/proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation
```

**Environment:**
 - Python version: 3.6
 - EODAG version: 2.0b2

**Comment by maximlt** [comment]
Also reported here: https://github.com/mapbox/rasterio/issues/2094
