### ISSUE TITLE
Directory not empty error

### ISSUE THREAD

**Issue by ctriquet-cs** [CS-SI/eodag#151]
**Describe the bug**

When calling the eodag API a "Directory not empty error" occurs.

**Code To Reproduce**
CLI commands or Python code snippet to reproduce the bug. Please use maximum verbosity using:
```python
import eodag
```

**Output**

```python
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/eodag/api/core.py", line 161, in build_index
        self.guess_product_type(eodagVersion=eodag_version)
      File "/usr/local/lib/python3.6/dist-packages/eodag/api/core.py", line 443, in guess_product_type
        raise NoMatchingProductType()
    eodag.utils.exceptions.NoMatchingProductType
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1988, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/usr/local/lib/python3.6/dist-packages/eodag_labextension/__init__.py", line 6, in <module>
        from eodag_labextension.handlers import RootHandler, ProductTypeHandler, SearchHandler
      File "/usr/local/lib/python3.6/dist-packages/eodag_labextension/handlers.py", line 9, in <module>
        from eodag.rest.utils import (
      File "/usr/local/lib/python3.6/dist-packages/eodag/rest/utils.py", line 32, in <module>
        eodag_api = eodag.EODataAccessGateway()
      File "/usr/local/lib/python3.6/dist-packages/eodag/api/core.py", line 106, in __init__
        self.build_index()
      File "/usr/local/lib/python3.6/dist-packages/eodag/api/core.py", line 166, in build_index
        shutil.rmtree(index_dir)
      File "/usr/lib/python3.6/shutil.py", line 490, in rmtree
        onerror(os.rmdir, path, sys.exc_info())
      File "/usr/lib/python3.6/shutil.py", line 488, in rmtree
        os.rmdir(path)
    OSError: [Errno 39] Directory not empty: '/home/qt/triquetc/.config/eodag/.index'
```

**Environment:**
 - Python version: 3.6.9
 - EODAG version: 2.0

**Additional context:**

Not sure, but this seemed to happen right after an eodag upgrade.

**Comment by sbrunato** [comment]
The issue seems related to `rmtree` usage with NFS, see https://github.com/spotify/luigi/issues/1665

I managed to reproduce the error when trying to delete an opened file on a NFS mounted directory:
```py
>>> import shutil
>>> from pathlib import Path
>>> Path('/home/ad/brunats/foo/').mkdir()
>>> Path('/home/ad/brunats/foo/bar').touch()
>>> f = open('/home/ad/brunats/foo/bar', 'r')
>>> shutil.rmtree('/home/ad/brunats/foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/shutil.py", line 490, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python3.6/shutil.py", line 488, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/ad/brunats/foo'
```
This won't work using a `rmtree` alternative either:
```py
>>> import subprocess
>>> subprocess.run("rm -rf /home/ad/brunats/foo", shell=True)
rm: cannot remove ‘/home/ad/brunats/foo/.nfs0000000003ed797100004fc6’: Device or resource busy
CompletedProcess(args='rm -rf /home/ad/brunats/foo', returncode=1)
```
The same thing on my local computer does not raise any error (with both `rmtree` and `subprocess.run`)

What can be done to bypass this issue, is to wait and retry that the file in closed

**Comment by sbrunato** [comment]
In our particular case, we have an error (when `$HOME` is on NFS) because when trying to delete `.index` it is still still opened until we exit the `except` block. See the following snippet that reproduces the error:
```py
import os
import shutil
from eodag import EODataAccessGateway
from eodag.utils.exceptions import NoMatchingProductType

dag = EODataAccessGateway()
index_dir = os.path.join(dag.conf_dir, ".index")
try:
    dag.guess_product_type(foo="bar")
except NoMatchingProductType:
    shutil.rmtree(index_dir)
    print("DELETED")
print("END")
```
`OSError: [Errno 39] Directory not empty: '/home/ad/brunats/.config/eodag/.index'`

And the same snippet with `rmtree` out of the `except` block:
```py
import os
import shutil
from eodag import EODataAccessGateway
from eodag.utils.exceptions import NoMatchingProductType

dag = EODataAccessGateway()
index_dir = os.path.join(dag.conf_dir, ".index")
create_index = False
try:
    dag.guess_product_type(foo="bar")
except NoMatchingProductType:
    create_index = True
finally:
    if create_index:
        shutil.rmtree(index_dir)
        print("DELETED")
print("END")
```
```
DELETED
END
```
This method is a good fix to our issue, we will use it to update `build_index()`
