### ISSUE TITLE
[Sobloo] Error in query

### ISSUE THREAD

**Issue by remi-braun** [CS-SI/eodag#155]
An error occured when querying a sobloo product (these products are offline)

The keywords of the search:
![2021-02-19_11h22_27](https://user-images.githubusercontent.com/67311115/108491888-c4fc3c80-72a4-11eb-95e7-4cabe2e63291.png)

The error:
![2021-02-19_11h14_38](https://user-images.githubusercontent.com/67311115/108491398-24a61800-72a4-11eb-9cdf-5c11f0e99a4f.png)

The function where it fails:
![2021-02-19_11h14_13](https://user-images.githubusercontent.com/67311115/108491396-240d8180-72a4-11eb-9210-7bc3f207742f.png)

The result:
![capture](https://user-images.githubusercontent.com/67311115/108491399-253eae80-72a4-11eb-9953-adacc5cabced.png)

**Comment by sbrunato** [comment]
Hello Remi, I think this already happened to me when the provider service fails and returns empty data. I did not manage to reproduce it as in general the service comes back quickly.
By the way, we will try to catch this and return an explicit message

**Comment by remi-braun** [comment]
Perfect !
It is really weird as sobloo fails for a product, but succeded for 3 others (also offline, also in 2016) right before...

Anyway, it is not impacting for me, it may just be the function classifying `storageStatus` that needs an exception ;)

**Comment by sbrunato** [comment]
If you manage to get a full Traceback of this error, please post it here, it will be very usefull.
Thanks

**Comment by remi-braun** [comment]
After a long inquiry:

```
Traceback (most recent call last):
  File "C:\Users\rbraun\Anaconda3\envs\satdownload\lib\site-packages\eodag\api\product\_product.py", line 96, in __init__
    product_geometry = wkt.loads(product_geometry)
  File "C:\Users\rbraun\Anaconda3\envs\satdownload\lib\site-packages\shapely\wkt.py", line 22, in loads
    return geos.WKTReader(geos.lgeos).read(data)
  File "C:\Users\rbraun\Anaconda3\envs\satdownload\lib\site-packages\shapely\geos.py", line 271, in read
    "Could not create geometry because of errors "
shapely.errors.WKTReadingError: Could not create geometry because of errors while reading input.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rbraun\Anaconda3\envs\satdownload\lib\site-packages\eodag\api\product\_product.py", line 99, in __init__
    product_geometry = wkb.loads(product_geometry)
  File "C:\Users\rbraun\Anaconda3\envs\satdownload\lib\site-packages\shapely\wkb.py", line 17, in loads
    return reader.read(data)
  File "C:\Users\rbraun\Anaconda3\envs\satdownload\lib\site-packages\shapely\geos.py", line 409, in read
    self._reader, c_char_p(data), c_size_t(len(data)))
TypeError: bytes or integer address expected instead of str instance
```

And a screenshot of the current state:
![2021-02-19_17h18_14](https://user-images.githubusercontent.com/67311115/108531350-e249fe80-72d6-11eb-865b-2381413c42d6.png)
![2021-02-19_17h21_39](https://user-images.githubusercontent.com/67311115/108531400-efff8400-72d6-11eb-8e1d-da1fb739afd3.png)

**Comment by maximlt** [comment]
I just hit a similar issue with the following snippet:
```python
from eodag.api.core import EODataAccessGateway
from eodag.utils.logging import setup_logging
setup_logging(verbose=3)
dag = EODataAccessGateway()
dag.set_preferred_provider("sobloo")
products, estimated_total_nbr_of_results = dag.search(
    productType='S2_MSI_L1C',
    start="2020-08-08",
    end="2020-08-10",
    geom=[137.772897, -37.134202, 153.749135, 73.885986],
    page=2,
    items_per_page=1150,
)
```

```
2021-02-22 13:21:37,171-15s eodag.config                     [INFO    ] (config           ) Loading user configuration from: /home/maxime/.config/eodag/eodag.yml
2021-02-22 13:21:37,452-15s eodag.core                       [DEBUG   ] (core             ) Opening product types index in /home/maxime/.config/eodag/.index
2021-02-22 13:21:37,462-15s eodag.core                       [INFO    ] (core             ) Locations configuration loaded from /home/maxime/.config/eodag/locations.yml
2021-02-22 13:21:37,601-15s eodag.core                       [INFO    ] (core             ) Searching product type 'S2_MSI_L1C' on provider: sobloo
2021-02-22 13:21:37,601-15s eodag.core                       [DEBUG   ] (core             ) Using plugin class for search: QueryStringSearch
2021-02-22 13:21:37,601-15s eodag.plugins.search.qssearch    [DEBUG   ] (qssearch         ) Mapping eodag product type to provider product type
2021-02-22 13:21:37,601-15s eodag.plugins.search.qssearch    [DEBUG   ] (qssearch         ) Getting provider product type definition parameters for S2_MSI_L1C
2021-02-22 13:21:37,601-15s eodag.plugins.search.qssearch    [DEBUG   ] (qssearch         ) Building the query string that will be used for search
2021-02-22 13:21:37,602-15s eodag.plugins.search.qssearch    [DEBUG   ] (qssearch         ) Retrieving queryable metadata from metadata_mapping
2021-02-22 13:21:37,602-15s eodag.plugins.search.qssearch    [INFO    ] (qssearch         ) Sending count request: https://sobloo.eu/api/v1/services/search?f=acquisition.beginViewingDate:gte:1596837600000&f=acquisition.endViewingDate:lte:1597010400000&f=identification.type:eq:S2MSI1C&gintersect=POLYGON ((137.7729 -37.1342, 137.7729 73.8860, 153.7491 73.8860, 153.7491 -37.1342, 137.7729 -37.1342))&size=1&from=0
2021-02-22 13:21:42,995-15s eodag.plugins.search.qssearch    [INFO    ] (qssearch         ) Sending search request: https://sobloo.eu/api/v1/services/search?f=acquisition.beginViewingDate:gte:1596837600000&f=acquisition.endViewingDate:lte:1597010400000&f=identification.type:eq:S2MSI1C&gintersect=POLYGON ((137.7729 -37.1342, 137.7729 73.8860, 153.7491 73.8860, 153.7491 -37.1342, 137.7729 -37.1342))&size=1150&from=1150
2021-02-22 13:21:45,423-15s eodag.plugins.search.qssearch    [DEBUG   ] (qssearch         ) Adapting plugin results to eodag product representation
2021-02-22 13:21:45,428-15s eodag.api.product.metadata_mapping [WARNING ] (metadata_mapping ) Could not extract property from Not Available using (?P<ONLINE>internal)|(?P<OFFLINE>external)
ParseException: Unknown type: 'NOT'
2021-02-22 13:21:45,448-15s eodag.core                       [INFO    ] (core             ) No result from provider 'sobloo' due to an error during search. Raise verbosity of log messages for details
2021-02-22 13:21:45,448-15s eodag.core                       [ERROR   ] (core             ) Error while searching on provider sobloo (ignored):
Traceback (most recent call last):
  File "/home/maxime/TRAVAIL/06_EODAG/01_eodag/eodag/eodag/api/product/_product.py", line 96, in __init__
    product_geometry = wkt.loads(product_geometry)
  File "/home/maxime/.pyenv/versions/eodag38/lib/python3.8/site-packages/shapely/wkt.py", line 22, in loads
    return geos.WKTReader(geos.lgeos).read(data)
  File "/home/maxime/.pyenv/versions/eodag38/lib/python3.8/site-packages/shapely/geos.py", line 289, in read
    raise WKTReadingError(
shapely.errors.WKTReadingError: Could not create geometry because of errors while reading input.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maxime/TRAVAIL/06_EODAG/01_eodag/eodag/eodag/api/core.py", line 654, in _do_search
    res, nb_res = search_plugin.query(**kwargs)
  File "/home/maxime/TRAVAIL/06_EODAG/01_eodag/eodag/eodag/plugins/search/qssearch.py", line 198, in query
    eo_products = self.normalize_results(
  File "/home/maxime/TRAVAIL/06_EODAG/01_eodag/eodag/eodag/plugins/search/qssearch.py", line 449, in normalize_results
    product = EOProduct(
  File "/home/maxime/TRAVAIL/06_EODAG/01_eodag/eodag/eodag/api/product/_product.py", line 99, in __init__
    product_geometry = wkb.loads(product_geometry)
  File "/home/maxime/.pyenv/versions/eodag38/lib/python3.8/site-packages/shapely/wkb.py", line 17, in loads
    return reader.read(data)
  File "/home/maxime/.pyenv/versions/eodag38/lib/python3.8/site-packages/shapely/geos.py", line 428, in read
    self._reader, c_char_p(data), c_size_t(len(data)))
TypeError: bytes or integer address expected instead of str instance
```

The search above should return no results, since sobloo has got 1102 products available for these criteria and I've set the page to 2 and items_per_page to 1150.

This [search URL](https://sobloo.eu/api/v1/services/search?f=acquisition.beginViewingDate:gte:1596837600000&f=acquisition.endViewingDate:lte:1597010400000&f=identification.type:eq:S2MSI1C&gintersect=POLYGON%20((137.7729%20-37.1342,%20137.7729%2073.8860,%20153.7491%2073.8860,%20153.7491%20-37.1342,%20137.7729%20-37.1342))&size=1150&from=1150) responds with:
```json
{
  "collection": "catalog",
  "nbhits": 0,
  "totalnb": 1102,
  "links": {
    "self": {
      "href": "https://sobloo.eu/api/v1/services/explore/explore/catalog/_search?f=acquisition.beginViewingDate%3Agte%3A1596837600000&f=acquisition.endViewingDate%3Alte%3A1597010400000&f=identification.type%3Aeq%3AS2MSI1C&gintersect=POLYGON%20%28%28137.7729%20-37.1342%2C%20137.7729%2073.8860%2C%20153.7491%2073.8860%2C%20153.7491%20-37.1342%2C%20137.7729%20-37.1342%29%29&size=1150&from=1150",
      "method": "GET"
    }
  }
}
```

From these lines https://github.com/CS-SI/eodag/blob/0eb6153aca99f0a51ad0e4bc0e5213b85d95c9f2/eodag/plugins/search/qssearch.py#L429-L431 it can be seen that the QueryStringSearch either gets a defined item from the response (`hits` for sobloo) or the whole response. This search doesn't return any `hits` so the whole response is retrieved. The code then tries to normalize these "results", which fails obviously.
