### ISSUE TITLE
Using .search_all with extent throws 'too many values to unpack (expected 2)'

### ISSUE THREAD

**Issue by rjdmartins** [CS-SI/eodag#268]
**Describe the bug**
Using .search_all() with a user defined bounding box extent throws the following error:
```
File "./eodag_search.py", line 44, in <module>
    geom=extent
ValueError: too many values to unpack (expected 2)
```

**Code To Reproduce**

```py
from eodag.utils.logging import setup_logging
from eodag.api.core import EODataAccessGateway

import os
import traceback

try:
    setup_logging(verbose=1)
    workspace = os.getcwd()
    print(workspace)
    dag = EODataAccessGateway(user_conf_file_path=os.path.join(workspace, 'user_conf_template.yml'))
    print(dag.get_preferred_provider())

    product_type = 'S2_MSI_L2A'
    extent = { 'latmin': 40.082143, 'latmax': 40.153556, 'lonmin': -8.749924, 'lonmax': -8.863564 }
    #extent = [-8.749924, 40.082143, -8.863564, 40.153556]
    #items_per_page=1000
    start='2016-06-01'
    end='2018-12-01'

    dag.set_preferred_provider(u'peps')
    products, _ = dag.search_all(
        #items_per_page=items_per_page,
        productType='S2_MSI_L2A',
        start=start,
        end=end,
        geom=extent
    )
    print(products)

    dag.set_preferred_provider(u'theia')
    print(dag.get_preferred_provider())
    products, _ = dag.search_all(
        #items_per_page=500,
        productType='S2_MSI_L2A_MAJA',
        start=start,
        end=end,
        geom=extent
    )
    print(products)
except Exception as e:
    print(e)
    print(traceback.format_exc())
```
In this code, I'm doing a search_all for Sentinel2 imagesets from each provider: THEIA and PEPS.
I'm forcing the change on provider using set_preferred_provider, and as you can see, the extent is a dictionary.
As you will see in the Outputs, after doing the search on PEPS for that extent using .search_all(), throws that error.
This bug does not occur if I use .search().
The reason for using search_all() is because I don't want to define a items_per_page limit for the search (i.e, I want providers to list all available products they have, but this is still limitating the search by assuming maxRecords=500 on the query)

**Output**
```
2021-04-27 15:46:43,967-15s eodag.config                     [INFO    ] Loading user configuration from: /home/ricardo/Worsica/user_conf_template.yml
2021-04-27 15:46:46,669-15s eodag.core                       [INFO    ] Locations configuration loaded from /home/ricardo/.config/eodag/locations.yml
('peps', 1)
2021-04-27 15:46:51,804-15s eodag.core                       [INFO    ] Searching product type 'S2_MSI_L2A' on provider: peps
2021-04-27 15:46:51,805-15s eodag.core                       [INFO    ] Searching product type 'S2_MSI_L2A' on provider: peps
2021-04-27 15:46:51,807-15s eodag.plugins.search.qssearch    [INFO    ] Sending search request: https://peps.cnes.fr/resto/api/collections/S2ST/search.json?startDate=2016-06-01&completionDate=2018-12-01&geometry=POLYGON ((-8.7499 40.0821, -8.7499 40.1536, -8.8636 40.1536, -8.8636 40.0821, -8.7499 40.0821))&productType=S2MSI2A&maxRecords=500&page=1
2021-04-27 15:47:07,861-15s eodag.core                       [INFO    ] Found 97 result(s) on provider 'peps'
too many values to unpack (expected 2)
Traceback (most recent call last):
  File "./eodag_search.py", line 27, in <module>
    geom=extent
ValueError: too many values to unpack (expected 2)
```
**Environment:**
 - Python version: 3.6.3
 - EODAG version: 2.2.0

**Additional context**
user_conf_template.yml
```
peps:
    #priority: 1 # Lower value means lower priority (Default: 1)
    #search:  # Search parameters configuration
    download:
        extract:  false # whether to extract the downloaded products (true or false).
        outputs_prefix: "/home/foo/bar" # where to store downloaded products.
        #dl_url_params:  # additional parameters to pass over to the download url as an url parameter
    auth:
        credentials:
            username: "foo@bar"
            password: "foobar"
theia:
    #priority: 0 # Lower value means lower priority (Default: 0)
    #search:   # Search parameters configuration
    download:
        extract: false
        outputs_prefix: "/home/foo/bar"
        #dl_url_params:
    auth:
        credentials:
            ident: "foo@bar"
            pass: "foobar"
``

**Comment by maximlt** [comment]
Hi @rjdmartins and thank you for this extended bug report :+1: 

The error `ValueError: too many values to unpack` usually means in Python that you have too many objects (on the right side of `=`) to assign to the variables (on the left side).

For instance:
```python
>>> a, b = (1, 2, 3)
ValueError: too many values to unpack (expected 2)
```

In your case, `dag.search_all` returns a `SearchResult` object. You shouldn't try to unpack it, since you don't know how many values it contains. This change you fix your code:
```python
    products = dag.search_all(
        #items_per_page=items_per_page,
        productType='S2_MSI_L2A',
        start=start,
        end=end,
        geom=extent
    )
```
(Note that I've remove `, _` after `products`, so the `SearchResult` returned by `search_all` will be assigned to `products`)

I think the confusion arises from the fact that the other search method, `search`, returns itself two elements:
```python
    products, total_count = dag.search(
        #items_per_page=items_per_page,
        productType='S2_MSI_L2A',
        start=start,
        end=end,
        geom=extent
    )
```

Please let me know if this change fixes your code.

**Comment by maximlt** [comment]
We have just updated the documentation, you can check it out to better understand the differences between `search` and `search_all`.

https://eodag.readthedocs.io/en/latest/ (this is not the stable version of the docs, it will be stable after the next release of EODAG)

**Comment by rjdmartins** [comment]
Hello maximlt. Thanks for the response.
Yes, the problem was with the second argument (the _ ) as output. Removed it and now works.
I'm closing this.
