### ISSUE TITLE
Trying to do the search it gives me 500 Server Error

### ISSUE THREAD

**Issue by MapperIT** [CS-SI/eodag#298]
Hi 

I was following the Eodag basic tutoial, when trying to do the search (point 6 of the code) it gives me the error. 

**Code To Reproduce**
```
import os

os.environ["EODAG__PEPS__AUTH__CREDENTIALS__USERNAME"] = "Username"
os.environ["EODAG__PEPS__AUTH__CREDENTIALS__PASSWORD"] = "Password"

import ipyleaflet as ipyl

# Create a workspace directory
workspace = 'eodag_workspace_basics'
if not os.path.isdir(workspace):
    os.mkdir(workspace)

# To have some basic feedback on what eodag is doing, we configure logging to output minimum information
from eodag.utils.logging import setup_logging
setup_logging(verbose=1)

from eodag.api.core import EODataAccessGateway

dag = EODataAccessGateway(os.path.join(workspace, 'eodag_conf.yml'))


from datetime import date

product_type = 'S2_MSI_L1C'
extent = {
    'lonmin': 0,
    'lonmax': 2,
    'latmin': 43,
    'latmax': 45
}

products, estimated_total_nbr_of_results = dag.search(
    productType=product_type,
    start='2018-06-01',
    end='2018-12-01',
    geom=extent
)
```

**The error message**
```
2021-06-09 15:27:19,144-15s eodag.core                       [INFO    ] Searching product type 'S2_MSI_L1C' on provider: peps
2021-06-09 15:27:19,147-15s eodag.plugins.search.qssearch    [INFO    ] Sending count request: https://peps.cnes.fr/resto/api/collections/S2ST/search.json?startDate=2018-06-01&completionDate=2018-12-01&geometry=POLYGON ((0.0000 43.0000, 0.0000 45.0000, 2.0000 45.0000, 2.0000 43.0000, 0.0000 43.0000))&productType=S2MSI1C&maxRecords=1&page=1
2021-06-09 15:29:19,417-15s eodag.plugins.search.qssearch    [ERROR   ] Skipping error while counting results for peps QueryStringSearch instance: 
Traceback (most recent call last):
  File "C:\Users\Katarina\AppData\Roaming\Python\Python38\site-packages\eodag\plugins\search\qssearch.py", line 655, in _request
    response.raise_for_status()
  File "c:\users\katarina\appdata\local\programs\python\python38\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://peps.cnes.fr/resto/api/collections/S2ST/search.json?startDate=2018-06-01&completionDate=2018-12-01&geometry=POLYGON%20((0.0000%2043.0000,%200.0000%2045.0000,%202.0000%2045.0000,%202.0000%2043.0000,%200.0000%2043.0000))&productType=S2MSI1C&maxRecords=1&page=1
2021-06-09 15:29:19,419-15s eodag.core                       [INFO    ] No result from provider 'peps' due to an error during search. Raise verbosity of log messages for details
2021-06-09 15:29:19,420-15s eodag.core                       [ERROR   ] Error while searching on provider peps (ignored):
Traceback (most recent call last):
  File "C:\Users\Katarina\AppData\Roaming\Python\Python38\site-packages\eodag\plugins\search\qssearch.py", line 655, in _request
    response.raise_for_status()
  File "c:\users\katarina\appdata\local\programs\python\python38\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://peps.cnes.fr/resto/api/collections/S2ST/search.json?startDate=2018-06-01&completionDate=2018-12-01&geometry=POLYGON%20((0.0000%2043.0000,%200.0000%2045.0000,%202.0000%2045.0000,%202.0000%2043.0000,%200.0000%2043.0000))&productType=S2MSI1C&maxRecords=1&page=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Katarina\AppData\Roaming\Python\Python38\site-packages\eodag\api\core.py", line 938, in _do_search
    res, nb_res = search_plugin.query(count=count, **kwargs)
  File "C:\Users\Katarina\AppData\Roaming\Python\Python38\site-packages\eodag\plugins\search\qssearch.py", line 206, in query
    self.search_urls, total_items = self.collect_search_urls(
  File "C:\Users\Katarina\AppData\Roaming\Python\Python38\site-packages\eodag\plugins\search\qssearch.py", line 396, in collect_search_urls
    _total_results = self.count_hits(
  File "C:\Users\Katarina\AppData\Roaming\Python\Python38\site-packages\eodag\plugins\search\qssearch.py", line 509, in count_hits
    response = self._request(
  File "C:\Users\Katarina\AppData\Roaming\Python\Python38\site-packages\eodag\plugins\search\qssearch.py", line 668, in _request
    raise RequestError(str(err))
eodag.utils.exceptions.RequestError: 500 Server Error: Internal Server Error for url: https://peps.cnes.fr/resto/api/collections/S2ST/search.json?startDate=2018-06-01&completionDate=2018-12-01&geometry=POLYGON%20((0.0000%2043.0000,%200.0000%2045.0000,%202.0000%2045.0000,%202.0000%2043.0000,%200.0000%2043.0000))&productType=S2MSI1C&maxRecords=1&page=1
```

**Environment:**
 - Python version: `python 3.8.7`
 - EODAG version: `eodag 2.2.0`

**Comment by sbrunato** [comment]
Hi @MapperIT ,

peps has some internal server issues at the moment. You may try another provider using (sobloo for example):
```py
dag.set_preferred_provider("sobloo")
```
This will set dynamically `sobloo` as the default provider (has to be done each time you instantiate `EODataAccessGateway`)

You can also save a new priority for providers in your user configuration file or also set it using system environment variables. See https://eodag.readthedocs.io/en/latest/getting_started_guide/configure.html

Please note that an automatic fallback mechanism is planned to be integrated, see https://github.com/CS-SI/eodag/issues/213

**Comment by MapperIT** [comment]
Hi @sbrunato 
Thank you!
