### ISSUE TITLE
Downloading issues for S2_MSI_L2A on mundi

### ISSUE THREAD

**Issue by dpriskinGEO** [CS-SI/eodag#349]
**Problem**
If I would like to use a provider, except PEPS all of them is giving me the same error meanwhile i defined all credentials and using the same output directory as I do with the PEPS. If I modify directly the config yaml it stops even at authentication.

**Code**
```
workspace = 'eodag_mundi'
os.environ["EODAG__MUNDI__AUTH__CREDENTIALS__APIKEY"] = "SECRET"
os.environ["EODAG__MUNDI__DOWNLOAD__OUTPUTS_PREFIX"] = os.path.abspath(workspace)
dag = eodag.EODataAccessGateway()
dag.set_preferred_provider("mundi")
products,total_count = dag.search(
  productType='S2_MSI_L2A',
  start="2021-08-02",
  end="2021-08-03",
  geom=shape_poly
)
print(total_count)
product_paths = dag.download_all(products)
```

**Output**

2021-09-29 13:03:09,039-15s eodag.plugins.download.base      [WARNING ] (base             ) A problem occurred during download of product: EOProduct(id=[[productname]], provider=mundi). Skipping it
2021-09-29 13:03:09,040-15s eodag.plugins.download.base      [DEBUG   ] (base             )

Traceback (most recent call last):
File "/home/miniconda3/envs/py38/lib/python3.8/site-packages/eodag/plugins/download/base.py", line 416, in download_all
    product.download(
File "/home/miniconda3/envs/py38/lib/python3.8/site-packages/eodag/api/product/_product.py", line 291, in download
    fs_path = self.downloader.download(
File "/home/miniconda3/envs/py38/lib/python3.8/site-packages/eodag/plugins/download/s3rest.py", line 207, in download
    with open(local_filename, "wb") as fhandle:
IsADirectoryError: [Errno 21] Is a directory: '/home/eodag_mundi/'

**Environment:**
 - Python version: `python 3.8`
 - EODAG version: `eodag version 2.3.3`

**Comment by sbrunato** [comment]
@dpriskinGEO thanks for reporting this issue!

I could reproduce this error when downloading `S2_MSI_L2A` products from `mundi`.

Other product types seem to work, and also `S2_MSI_L2A` with other providers (I just checked `creodias`)

See available providers using:
```py
dag.available_providers(product_type="S2_MSI_L2A")
['astraea_eod', 'aws_eos', 'creodias', 'earth_search', 'mundi', 'onda', 'peps', 'sobloo']
```

If you also had errors using other providers or product types, please post it to help us fix it.
Thank you
