### ISSUE TITLE
Issue on page /notebooks/tutos/tuto_ship_detection.html

### ISSUE THREAD

**Issue by craigmpearce** [CS-SI/eodag#386]
Hi,

I run the code provided below with the attached config file in Pycharm on Linux OS and everything works fine. When run in Pycharm on Windows 10, the below error occurs. This error occurs for PEPS and for other providers that the code previously worked for. There does not seem to be any information on this website (or anywhere else online) so it is not possible to to understand then fix the issue. Please can you help me?

All the best

Craig

#############
Code to be run #
#############

# Link to SNAP Toolbox
snap_link ="C:\\Program Files\\snap\\bin"

# Name of config file
config_file = "eodag.yml"

# Set coordinates
lonmin = 13.01
lonmax = 13.9
latmin = 45.1
latmax = 45.9

# Set start and end date
start_date = "2021-05-01"
end_date = "2021-05-03"

# Select product type
product_type = "S1_SAR_GRD"

# Install packages
import os
import folium
from folium import plugins
import imageio
import matplotlib.pyplot as plt
import numpy as np
import rasterio as rio

from eodag.api.core import EODataAccessGateway
from eodag import setup_logging

# Add absolute path to SNAP bin folder to make the gpt command available
os.environ["PATH"] = snap_link + ":" + os.environ["PATH"]

# Set working directory
base_wd = os.getcwd()
os.chdir(base_wd)

# Create the workspace folder
workspace = 'eodag_workspace_shipdetection'
if not os.path.isdir(workspace):
    os.mkdir(workspace)

# Move config file into workspace then start EODAG
if not os.path.isfile(os.path.join(base_wd, workspace, config_file)):
    os.rename(os.path.join(base_wd, config_file), os.path.join(base_wd, workspace, config_file))
dag = EODataAccessGateway(os.path.join(base_wd, workspace, config_file))

# Search for products in time and space
products, total_count = dag.search(
   productType=product_type,
   start=start_date,
   end=end_date,
   geom={"lonmin": lonmin, "latmin": latmin, "lonmax": lonmax, "latmax": latmax}
)
print(f"Got {total_count} products.")

#############
Error message ##
#############

Access violation - no RTTI data!
Error while searching on provider peps (ignored):
Traceback (most recent call last):
  File "C:\Users\craig\PycharmProjects\Download_process_imagery\venv\lib\site-packages\eodag\api\core.py", line 1037, in _do_search
    res, nb_res = search_plugin.query(count=count, **kwargs)
  File "C:\Users\craig\PycharmProjects\Download_process_imagery\venv\lib\site-packages\eodag\plugins\search\qssearch.py", line 225, in query
    qp, qs = self.build_query_string(product_type, **keywords)
  File "C:\Users\craig\PycharmProjects\Download_process_imagery\venv\lib\site-packages\eodag\plugins\search\qssearch.py", line 307, in build_query_string
    format_metadata(provider_value, product_type, **kwargs)
  File "C:\Users\craig\PycharmProjects\Download_process_imagery\venv\lib\site-packages\eodag\api\product\metadata_mapping.py", line 368, in format_metadata
    return MetadataFormatter().vformat(search_param, args, kwargs)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python38\lib\string.py", line 167, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python38\lib\string.py", line 211, in _vformat
    obj = self.convert_field(obj, conversion)
  File "C:\Users\craig\PycharmProjects\Download_process_imagery\venv\lib\site-packages\eodag\api\product\metadata_mapping.py", line 182, in convert_field
    converted = self.custom_converter(value)
  File "C:\Users\craig\PycharmProjects\Download_process_imagery\venv\lib\site-packages\eodag\api\product\metadata_mapping.py", line 204, in convert_to_rounded_wkt
    wkt_value = wkt.dumps(value, rounding_precision=COORDS_ROUNDING_PRECISION)
  File "C:\Users\craig\PycharmProjects\Download_process_imagery\venv\lib\site-packages\shapely\wkt.py", line 62, in dumps
    return geos.WKTWriter(geos.lgeos, trim=trim, **kw).write(ob)
  File "C:\Users\craig\PycharmProjects\Download_process_imagery\venv\lib\site-packages\shapely\geos.py", line 402, in write
    text = string_at(result)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 514, in string_at
    return _string_at(ptr, size)
OSError: exception: access violation reading 0x0000000000000000
Exception ignored in: <function BaseGeometry.__del__ at 0x000002369631AD30>

Traceback (most recent call last):
  File "C:\Users\craig\PycharmProjects\Download_process_imagery\venv\lib\site-packages\shapely\geometry\base.py", line 209, in __del__
    self._empty(val=None)
  File "C:\Users\craig\PycharmProjects\Download_process_imagery\venv\lib\site-packages\shapely\geometry\base.py", line 194, in _empty
    self._lgeos.GEOSGeom_destroy(self.__geom__)
OSError: exception: access violation writing 0x0000000000000000
Got 0 products.

[eodag_test.txt](https://github.com/CS-SI/eodag/files/7863700/eodag_test.txt)

**Comment by sbrunato** [comment]
Hello @craigmpearce , and thanks for reporting your issue. We'll try to check and reproduce your error and then get back to you

**Comment by craigmpearce1** [comment]
Hi @sbrunato thank you for looking into this for me. I wanted to ask if you have made progress on this?

**Comment by sbrunato** [comment]
> Hi @sbrunato thank you for looking into this for me. I wanted to ask if you have made progress on this?

Please try to update or re-install `shapely` to see if this can solve the issue. The issue seems to be related to your environment

**Comment by craigmpearce1** [comment]
Trying several different potential solutions including uninstalling, reinstalling then updating shapely (and some other related packages) did not work. Will persist with this to find a solution. Regarding the issues with the shapefiles, below is a link to the STEP Forum where a successful solution was proposed https://forum.step.esa.int/t/failed-to-import-geometry-with-particular-shapefiles-when-using-eodag-and-xml-config-files/34863/5
