### ISSUE TITLE
Mass download issue with creodias and sobloo

### ISSUE THREAD

**Issue by dpriskinGEO** [CS-SI/eodag#437]
**Describe the bug**
When I try to download a lot of Sentinel-2 products (around 2000), at some point the EODAG breaks. The code worked perfectly for months.

**Output**

```
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://auth.creodias.eu/auth/realms/dias/protocol/openid-connect/token
```

**Environment:**
 - Python version: `Python 3.10.4`
 - EODAG version: `2.4.0`

**Comment by sbrunato** [comment]
Hello @dpriskinGEO , and thanks for reporting this issue. 
Could you give us more details on how you perform search & download ? 
Using several `search()` or a `search_all`, downloading using `download()` in a loop, or `download_all` ? with some particular parameters ? 
Thanks

**Comment by dpriskinGEO** [comment]
@sbrunato 

```
Traceback (most recent call last):
  File "/home/dp/miniconda3/envs/dag310/lib/python3.10/site-packages/eodag/plugins/authentication/keycloak.py", line 55, in authenticate
    response.raise_for_status()
  File "/home/dp/miniconda3/envs/dag310/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://auth.creodias.eu/auth/realms/dias/protocol/openid-connect/token
```
