### ISSUE TITLE
Creodias identity changed - unauthorized?

### ISSUE THREAD

**Issue by ds2268** [CS-SI/eodag#512]
**Describe the bug**

Creodias download API stopped working recently!

After properly setting up eodag.yaml with credentials I get an unauthorized error (401) on product download.

I contacted Creodias support and answered that the identity has changed and that this might be the cause of the problem. They provided the following link for more details:

https://creodias.eu/-/how-to-download-eodata-products-using-eofinder-api-

**Code To Reproduce**

```py
from eodag.utils.logging import setup_logging
setup_logging(verbose=3)

....

dl_path_l1c = rnd_product.download() # fails for any product
```

**Output**

```
Traceback (most recent call last):
  File "/home/dejans/miniconda3/envs/lidar-preprocessing/lib/python3.9/site-packages/eodag/plugins/download/http.py", line 155, in download
    stream.raise_for_status()
  File "/home/dejans/miniconda3/envs/lidar-preprocessing/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://zipper.creodias.eu/download/e9cedae0-1395-513e-86d0-97d1b97e8027?token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ5RUhvWks0aWR2WHFmeExZWFhabjFmTi1YSU1UTXJvdTJ2NmVIQXI5ZWE0In0.eyJleHAiOjE2NjQzMTU3NzYsImlhdCI6MTY2NDI3OTc3NiwianRpIjoiNzFkZTE4YWEtMzAyOC00ZjUzLTg0YjUtZjA2Nzc4ODRjM2RlIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLmNyZW9kaWFzLmV1L2F1dGgvcmVhbG1zL2RpYXMiLCJhdWQiOlsiQ0xPVURGRVJST19QQVJUTkVSUyIsImFjY291bnQiXSwic3ViIjoiYjM2NjYxZDUtMGNlYi00YTUyLTgyNjYtYzIyN2NlYjUwZTNkIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiQ0xPVURGRVJST19QQVJUTkVSUyIsInNlc3Npb25fc3RhdGUiOiIwYmIyZGI4Ni04Y2I0LTRjZTEtYTY3Yy03YTQ2YzRlOTdjZDEiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vZmluZGVyMi5pbnRyYS5jbG91ZGZlcnJvLmNvbS8qIiwiaHR0cHM6Ly9ob3Jpem9uLmNmMi5jbG91ZGZlcnJvLmNvbSIsImh0dHBzOi8vZmluZGVyLmNyZW9kaWFzLmV1IiwiaHR0cHM6Ly9wb3J0YWwuY3Jlb2RpYXMuZXUiLCJodHRwczovL2NmMi5jbG91ZGZlcnJvLmNvbSIsImh0dHBzOi8vZGlzY292ZXJ5LmNyZW9kaWFzLmV1IiwiKiIsImh0dHBzOi8vMTg1LjE3OC44NS4yMjIiLCJodHRwczovL3d3dy5jcmVvZGlhcy5ldSIsImh0dHBzOi8vZGFzaGJvYXJkLmNyZW9kaWFzLmV1IiwiaHR0cHM6Ly9zZXJ2aWNlcy5zZW50aW5lbC1odWIuY29tIiwiaHR0cHM6Ly93aG1jcy5jbG91ZGZlcnJvLmNvbSIsImh0dHBzOi8vMTg1LjE3OC44NC4xOCIsImh0dHBzOi8vYXV0aC5jbG91ZC5jb2RlLWRlLm9yZy8qIiwiaHR0cHM6Ly9wb3J0YWwuY3Jlb2RpYXMuZXUvKiIsImh0dHBzOi8vZmluZGVyZGV2LmludHJhLmNsb3VkZmVycm8uY29tIiwiaHR0cHM6Ly9jcmVvZGlhcy5ldSIsImh0dHBzOi8vY3Jlb2FwcHMuc2VudGluZWwtaHViLmNvbS8qIiwiaHR0cDovL2ZpbmRlcjIuaW50cmEuY2xvdWRmZXJyby5jb20iLCJodHRwczovL2Jyb3dzZXIuY3Jlb2RpYXMuZXUiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1kaWFzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgYXVkLWZpeC1wYXJ0bmVycyBhZGRyZXNzIGVtYWlsIiwic2lkIjoiMGJiMmRiODYtOGNiNC00Y2UxLWE2N2MtN2E0NmM0ZTk3Y2QxIiwiYWRkcmVzcyI6e30sImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IkRlamFuIFN0ZXBlYyIsInByZWZlcnJlZF91c2VybmFtZSI6ImRlamFuLnN0ZXBlY0B4bGFiLnNpIiwiZ2l2ZW5fbmFtZSI6IkRlamFuIiwiZmFtaWx5X25hbWUiOiJTdGVwZWMiLCJlbWFpbCI6ImRlamFuLnN0ZXBlY0B4bGFiLnNpIn0.TG47io_OWxnl7F3rg-nQmoqdvnpzpr-eEJ8IT87fRCrE_UT89G2O2110PYw9BjfV_fFbwGHF-ZUfpeoFixmA6omeym9oBrKHAfOySxTndNNVaP85qducmAp2AxA9Jrsg7XPrdPQLK6XIy9D-fXqQgdiw8bmS38WQJTedH_ifzYviJv751z79sfTeW0zP66IOWyGyeETp1KicSY5azfoj2CdcmeRAuj9N36xarPyk8kqT4dPouw6n416wVAxrK3eVSx1FqDfczMEcj18pGjxmd4dX4y8MV9EgY2nvBRhIVj68tcX0LpfBwsSfaAsDg0t1UWJ9BiSTjryjwzTRFpNMBg
```

**Environment:**
 - Python version: Python 3.9.0
 - EODAG version: eodag (Earth Observation Data Access Gateway): version 2.5.2

**Comment by sbrunato** [comment]
Thank you very much for reporting this issue @ds2268 . We'll fix it soon

**Comment by ds2268** [comment]
Thanks! That would be really appreciated, as the Creodias provider is of few that has a full archive online for quick access. Especially useful if you work a lot with satellite imagery data that is 2yrs+ old.
