### ISSUE TITLE
Problem to download Sentinel2 and Landsat using onda and usgs providers

### ISSUE THREAD

**Issue by felipefariadesousa** [CS-SI/eodag#617]
I am trying to download Sentinel 2 images from the onda provider and Landat images from the usgs provider, but I am having problems downloading them. For example, I searched for a point between two dates and got two images that met this condition, but when I download both images I get this warning:

[WARNING ] A problem occurred during download of product: EOProduct(id=S2B_MSIL1C_20210106T131239_N0209_R138_T23KMP_20210106T145736, provider=onda). Skipping it

Link: [https://drive.google.com/file/d/1UuJlgjlpZ1JLi7VJoXdXUVYO2IjMFsAe/view?usp=sharing](url)

**Comment by sbrunato** [comment]
Hello @felipefariadesousa , and many thanks for submitting this issue.
With increased logging using `setup_logging(3)`, we can get for your example the following error:
```
Traceback (most recent call last):
  File "/home/sylvain/workspace/eodag/eodag/plugins/download/base.py", line 453, in download_all
    product.download(
  File "/home/sylvain/workspace/eodag/eodag/api/product/_product.py", line 313, in download
    fs_path = self.downloader.download(
  File "/home/sylvain/workspace/eodag/eodag/plugins/download/http.py", line 280, in download
    self.orderDownload(product=product, auth=auth)
  File "/home/sylvain/workspace/eodag/eodag/plugins/download/http.py", line 106, in orderDownload
    query_dict = geojson.loads(parts.query)
  File "/home/sylvain/.virtualenvs/eodag-dev/lib/python3.8/site-packages/geojson/codec.py", line 51, in loads
    return json.loads(s,
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
This is caused by a JSON decoding issue during the OFFLINE product ordering process.
A fix will be applied for it soon.
