### ISSUE TITLE
Timeout sometimes reached with search_all 

### ISSUE THREAD

**Issue by josselin-aval** [CS-SI/eodag#650]
When running the following code : 

```py
from eodag import EODataAccessGateway

# init the eodag object
dag = EODataAccessGateway()

# query eodag
search_results = dag.search_all(
productType='S2_MSI_L1C',
# the geojson is supposed to have 1 polygon
geom=feature["geometry"][0], # accepts WKT polygons, shapely.geometry, ...
start="2018-01-01",
end="2018-01-15"
)
```

With `feature["geometry"][0]` being a shapely polygon : 
`
POLYGON ((-73.24993888888889 -42.51593611111111, -73.25799722222222 -42.51612222222222, -73.25734166666666 -42.51266388888889, -73.24988888888889 -42.515166666666666, -73.24993888888889 -42.51593611111111))`

I obtain sometimes the following error :

```
Skipping error while searching for peps QueryStringSearch instance: 
Traceback (most recent call last):
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='peps.cnes.fr', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/eodag/plugins/search/qssearch.py", line 910, in _request
    response = requests.get(url, timeout=HTTP_REQ_TIMEOUT, **kwargs)
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/aval/Desktop/eodag/venv/lib/python3.9/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='peps.cnes.fr', port=443): Read timed out. (read timeout=5)
```

This is not specific to these areas and dates.

Is this because I make too many requests? Is there any quota? Is it possible to be blocked?

Thank you in advance for your help.

**Comment by sbrunato** [comment]
Hello @josselin-aval , peps is under maintenance since some days, see https://peps-mission.cnes.fr/en/search/site/Peps.
That's why you get timeout errors when searching on it. You may search on a different provider, modifying other providers priority in your configuration file, or changing dynamically https://eodag.readthedocs.io/en/stable/notebooks/api_user_guide/3_configuration.html#Set-a-provider's-priority

**Comment by josselin-aval** [comment]
Hello @sbrunato , thank you very much for your explanation and proposal, I will test that.
