### ISSUE TITLE
Extracting downloaded zip files is failing

### ISSUE THREAD

**Issue by iliion** [CS-SI/eodag#785]
**Describe the bug**
Extracting downloaded zip files is failing. 

**Code To Reproduce**
 
```py
    workspace = 'workspace'
    if not os.path.isdir(workspace):
        os.mkdir(workspace)
    outputs_prefix = os.path.abspath(workspace)

    user_conf_path = working_dir_path / "conf.yml"
    locations_conf_path = working_dir_path / "locations.yml"
    dag = EODataAccessGateway(user_conf_file_path=str(user_conf_path), locations_conf_path=str(locations_conf_path))
    dag.set_preferred_provider("cop_dataspace")

    search_criteria = {
        "productType": "S2_MSI_L2A",
        "start": "2023-08-01",
        "end": "2023-08-09",
        "geom": (9, 39, 7, 41),
        "cloudCover": 70,
    }
    all_products = dag.search_all(**search_criteria, items_per_page=300)

    product_paths = dag.download_all(all_products, outputs_prefix=outputs_prefix)
```

**Output**

```shell
2023-08-08 17:20:33,658 eodag.plugins.download.base      [DEBUG   ] (base             ) 
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\eodag\plugins\download\base.py", line 453, in download_all
    product.download(
  File "C:\Python39\lib\site-packages\eodag\api\product\_product.py", line 323, in download
    fs_path = self.downloader.download(
  File "C:\Python39\lib\site-packages\eodag\plugins\download\http.py", line 498, in download
    return download_request(
  File "C:\Python39\lib\site-packages\eodag\plugins\download\base.py", line 561, in download_and_retry
    return download(*args, **kwargs)
  File "C:\Python39\lib\site-packages\eodag\plugins\download\http.py", line 492, in download_request
    product_path = self._finalize(
  File "C:\Python39\lib\site-packages\eodag\plugins\download\base.py", line 333, in _finalize
    zfile.extract(
  File "C:\Python39\lib\zipfile.py", line 1616, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Python39\lib\zipfile.py", line 1687, in _extract_member
    open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\my_user\\AppData\\Local\\Temp\\tmpin1ubp39\\S2A_MSIL2A_20230801T100601_N0509_R022_T32SLJ_20230801T161353.SAFE\\S2A_MSIL2A_20230801T100601_N0509_R022_T32SLJ_20230801T161353.SAFE\\DATASTRIP\\DS_2APS_20230801T161353_S20230801T100834\\QI_DATA\\FORMAT_CORRECTNESS.xml'
``` 

---

**Environment:**
 - Python version: `3.9.5`
 - EODAG version: `2.9.1`

**Additional context**
The zip files are downloaded correctly in the created `workspace` folder, but during the zip file extraction `eodag` is looking in the Temp folder (?!).

**Comment by iliion** [comment]
Ping ping :]

**Comment by sbrunato** [comment]
Hello @iliion , tmp directory is used to temporary extract files before moving them. 
Your error seams windows-related. See https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

Path is longer than 260 characters which is the default limit for paths on this OS. 
We may try to use `\\?\` prefix in windows paths to enable longer paths.
Until this is implemented, you can try to set `LongPathsEnabled` in your registry like explained on MS documentation.

**Comment by iliion** [comment]
ok Thanks a lot. I was not aware of that
