### ISSUE TITLE
Hard-coded timeout is too short in search request on PEPS

### ISSUE THREAD

**Issue by koleckt** [CS-SI/eodag#908]
**Bug description**
When a search request is done, there is an hard-coded timeout in "request" library. This timeout is 5 seconds and sometimes (depending on the charge) PEPS needs more time to initiate the http connection. So an error occurs.

Currently, the errors occurs statistically every 100 requests on PEPS.

Bug correction proposal: Allow changing this 5 seconds timeout to an higher value with a parameter

**Python line in the script that generate error**

When executing a large number of search request on PEPS like that:
```py
products_ipage, estimated_total_number = dag.search(page=1, items_per_page=200,raise_errors =True, **search_criteria)
```

**Output**
```
Skipping error while searching for peps QueryStringSearch instance: 
Traceback (most recent call last):
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='peps.cnes.fr', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/eodag/plugins/search/qssearch.py", line 961, in _request
    response = requests.get(
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/work/scratch/env/koleckt/.conda/envs/dev-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='peps.cnes.fr', port=443): Read timed out. (read timeout=5)
```

**Environment:**
 - EODAG version: latest

**Additional context**
Data provider is PEPS.

**Comment by sbrunato** [comment]
Hello @koleckt , and thanks for submitting this issue. Such a feature is already available on the [develop](https://github.com/CS-SI/eodag/tree/develop) branch and will be available with the next stable version.
See https://github.com/CS-SI/eodag/pull/841
This timeout can be set in your `~/.config/eodag/eodag.yml` (`peps.search.timeout`), or using environment variable:
```py
os.environ["EODAG__PEPS__SEARCH__TIMEOUT"] = "10"
```
