### ISSUE TITLE
TimeoutError: The read operation timed out

### ISSUE THREAD

**Issue by msordi** [CS-SI/eodag#973]
**Describe the bug**
When i try to download all Hydroweb rivers on [hydro](https://hydroweb.next.theia-land.fr/) portal, i got a TimeoutError.
The collection i want to download contains more than 20_000 items.

**Code To Reproduce**

```py
help_message = """
Download products from your Hydroweb.next project (https://hydroweb.next.theia-land.fr) using EODAG (https://github.com/CS-SI/eodag)
This script is an example tuned for your last Hydroweb.next project but feel free to adapt it for future requests.
Follow these steps:
1. If not already done, install EODAG and packaging latest version using `pip install -U eodag packaging` or `conda update eodag packaging`
2a. Generate an API-Key from Hydroweb.next portal in your user settings
2b. Carefully store your API-Key
- either in your eodag configuration file (usually ~/.config/eodag/eodag.yml, automatically generated the first time you use eodag) in auth/credentials/apikey="PLEASE_CHANGE_ME"
- or in an environment variable `export EODAG__HYDROWEB_NEXT__AUTH__CREDENTIALS__APIKEY="PLEASE_CHANGE_ME"`
3. You can change download directory by modifying the variable path_out. By default, current path is used.
4. You are all set, run this script `python download_Theia_Hydroweb_Altimetry_River_Water_Level.py`

For more information, please refer to EODAG Documentation https://eodag.readthedocs.io
"""
try:
    import os
    from eodag import EODataAccessGateway, SearchResult
    from eodag import __version__ as eodag_version
    from eodag import setup_logging
    from packaging import version

    assert version.parse(eodag_version) >= version.parse("2.10.0"), help_message
except ImportError:
    print(help_message)
    exit(1)

setup_logging(3)  # 0: nothing, 1: only progress bars, 2: INFO, 3: DEBUG

dag = EODataAccessGateway()

# --------------------------------------------------
# Declare the path where the file will be downloaded
# Set to /tmp if path is incorrect
path_out = os.getcwd()

if not os.path.isdir(path_out):
    path_out = "/tmp"

# ---------------------------------------------------------------------------------------------------------------------
# Use this code-block to define your search criteria. It defines a list of query-arguments dictionaries.
# Each query-arguments dictionary will be used to perform a distinct search, whose results will then be concatenated.
#   - add/remove collections using the `productType` key (one per query-arguments dictionary)
#   - add time restrictions using the `start` and `end` keys (e.g. "start": "2020-05-01" , "end": "2020-05-10T00:00:00Z",
#     UTC ISO8601 format)(one per collection/dictionary)
#   - add spatial restrictions using the "geom" key (e.g. "geom": "POLYGON ((1 43, 2 43, 2 44, 1 44, 1 43))" WKT string,
#       a bounding-box list [lonmin, latmin, lonmax, latmax] can also be passed )(one per collection/dictionary)
#   - more query arguments can be used, see
#     https://eodag.readthedocs.io/en/stable/notebooks/api_user_guide/4_search.html?#Search-parameters
#     project_query_args = [
#         {"productType":"SWOT_L2_HR_RASTER_250M_SAMPLE_V1_2","geom":"POLYGON ((-4.17 43.10,12.70 43.10,12.70 49.64,-4.17 49.64,-4.17 43.10))"}]
#
# This code-block searches for matching products in Hydroweb.next STAC API catalog. No need to modify.
#     project_search_results = SearchResult([])
#     for query_args in project_query_args:
#         project_search_results.extend(dag.search_all(**query_args))
# This command will perform a search using provided query arguments.
# - specify a collection using the `productType` key
# - add time restrictions using the `start` and `end` keys (e.g. "start": "2020-05-01" , "end": "2020-05-10T00:00:00Z",
#   UTC ISO8601 format)
# - add spatial restrictions using the "geom" key (e.g. "geom": "POLYGON ((1 43, 2 43, 2 44, 1 44, 1 43))" WKT string,
#   a bounding-box list [lonmin, latmin, lonmax, latmax] can also be passed )
# - more query arguments can be used, see
#   https://eodag.readthedocs.io/en/stable/notebooks/api_user_guide/4_search.html?#Search-parameters
search_results = dag.search_all(
    productType="HYDROWEB_RIVERS",
)
# This command actually downloads the matching products
downloaded_paths = dag.download_all(search_results, outputs_prefix=path_out)
if downloaded_paths:
    print(f"files successfully downloaded in {downloaded_paths}")
else:
    print(f"No files downloaded! Verify API-KEY and/or product search configuration.")

```

**Output**
```sh
2024-01-08 09:58:44,911 eodag.config                     [DEBUG   ] (tid=139964798083072) Loading configuration from /home/msordi/.local/lib/python3.10/site-packages/eodag/resources/providers.yml
2024-01-08 09:58:45,644 eodag.config                     [INFO    ] (tid=139964798083072) Loading user configuration from: /home/msordi/.config/eodag/eodag.yml
2024-01-08 09:58:45,657 eodag.core                       [INFO    ] (tid=139964798083072) usgs: provider needing auth for search has been pruned because no crendentials could be found
2024-01-08 09:58:45,657 eodag.core                       [INFO    ] (tid=139964798083072) aws_eos: provider needing auth for search has been pruned because no crendentials could be found
2024-01-08 09:58:45,657 eodag.core                       [INFO    ] (tid=139964798083072) meteoblue: provider needing auth for search has been pruned because no crendentials could be found
2024-01-08 09:58:45,657 eodag.core                       [INFO    ] (tid=139964798083072) wekeo: provider needing auth for search has been pruned because no crendentials could be found
2024-01-08 09:58:45,661 eodag.core                       [DEBUG   ] (tid=139964798083072) Opening product types index in /home/msordi/.config/eodag/.index
2024-01-08 09:58:45,667 eodag.core                       [DEBUG   ] (tid=139964798083072) Out-of-date product types index removed from /home/msordi/.config/eodag/.index
2024-01-08 09:58:45,667 eodag.core                       [DEBUG   ] (tid=139964798083072) Creating product types index in /home/msordi/.config/eodag/.index
2024-01-08 09:58:45,724 eodag.core                       [INFO    ] (tid=139964798083072) Locations configuration loaded from /home/msordi/.config/eodag/locations.yml
2024-01-08 09:58:45,724 eodag.core                       [DEBUG   ] (tid=139964798083072) Fetching external product types sources to find HYDROWEB_RIVERS product type
2024-01-08 09:58:45,724 eodag.config                     [INFO    ] (tid=139964798083072) Fetching external product types from https://cs-si.github.io/eodag/eodag/resources/ext_product_types.json
2024-01-08 09:58:45,905 eodag.core                       [DEBUG   ] (tid=139964798083072) Added product types ['mod11a1', 'mod13a1', 'myd11a1', 'myd13a1', 'maxar_open_data', 'spacenet7', 'umbra_open_data'] for astraea_eod
2024-01-08 09:58:45,909 eodag.core                       [DEBUG   ] (tid=139964798083072) Added product types ['Sentinel1RTC', 'Sentinel2', 'Sentinel6', 'Landsat5', 'Landsat7', 'Landsat8', 'Envisat', 'SMOS', 'S2GLC'] for creodias
2024-01-08 09:58:46,003 eodag.core                       [DEBUG   ] (tid=139964798083072) Added product types ['daymet-annual-pr', 'daymet-daily-hi', '3dep-seamless', '3dep-lidar-dsm', 'fia', 'sentinel-1-rtc', 'gridmet', 'daymet-annual-na', 'daymet-monthly-na', 'daymet-annual-hi', 'daymet-monthly-hi', 'daymet-monthly-pr', 'gnatsgo-tables', 'hgb', 'cop-dem-glo-30', 'cop-dem-glo-90', 'goes-cmi', 'terraclimate', 'nasa-nex-gddp-cmip6', 'gpm-imerg-hhr', 'gnatsgo-rasters', '3dep-lidar-hag', '3dep-lidar-intensity', '3dep-lidar-pointsourceid', 'mtbs', 'noaa-c-cap', '3dep-lidar-copc', 'modis-64A1-061', 'alos-fnf-mosaic', '3dep-lidar-returns', 'mobi', 'era5-pds', 'chloris-biomass', 'kaza-hydroforecast', 'planet-nicfi-analytic', 'modis-17A2H-061', 'modis-11A2-061', 'daymet-daily-pr', '3dep-lidar-dtm-native', '3dep-lidar-classification', '3dep-lidar-dtm', 'gap', 'modis-17A2HGF-061', 'planet-nicfi-visual', 'gbif', 'modis-17A3HGF-061', 'modis-09A1-061', 'alos-dem', 'alos-palsar-mosaic', 'deltares-water-availability', 'modis-16A3GF-061', 'modis-21A2-061', 'us-census', 'jrc-gsw', 'deltares-floods', 'modis-09Q1-061', 'modis-14A1-061', 'hrea', 'modis-13Q1-061', 'modis-14A2-061', 'modis-15A2H-061', 'modis-11A1-061', 'modis-15A3H-061', 'modis-13A1-061', 'daymet-daily-na', 'nrcan-landcover', 'modis-10A2-061', 'ecmwf-forecast', 'noaa-mrms-qpe-24h-pass2', 'nasadem', 'io-lulc', 'drcog-lulc', 'chesapeake-lc-7', 'chesapeake-lc-13', 'chesapeake-lu', 'noaa-mrms-qpe-1h-pass1', 'noaa-mrms-qpe-1h-pass2', 'noaa-nclimgrid-monthly', 'goes-glm', 'usda-cdl', 'eclipse', 'esa-cci-lc', 'esa-cci-lc-netcdf', 'fws-nwi', 'usgs-lcmap-conus-v13', 'usgs-lcmap-hawaii-v10', 'noaa-climate-normals-tabular', 'noaa-climate-normals-netcdf', 'noaa-climate-normals-gridded', 'aster-l1t', 'cil-gdpcir-cc-by-sa', 'io-lulc-9-class', 'io-biodiversity', 'noaa-cdr-sea-surface-temperature-whoi', 'noaa-cdr-ocean-heat-content', 'cil-gdpcir-cc0', 'cil-gdpcir-cc-by', 'noaa-cdr-sea-surface-temperature-whoi-netcdf', 'noaa-cdr-sea-surface-temperature-optimum-interpolation', 'modis-10A1-061', 'sentinel-5p-l2-netcdf', 'sentinel-3-olci-wfr-l2-netcdf', 'noaa-cdr-ocean-heat-content-netcdf', 'sentinel-3-synergy-aod-l2-netcdf', 'sentinel-3-synergy-v10-l2-netcdf', 'sentinel-3-olci-lfr-l2-netcdf', 'sentinel-3-sral-lan-l2-netcdf', 'sentinel-3-slstr-lst-l2-netcdf', 'sentinel-3-slstr-wst-l2-netcdf', 'sentinel-3-sral-wat-l2-netcdf', 'ms-buildings', 'sentinel-3-slstr-frp-l2-netcdf', 'sentinel-3-synergy-syn-l2-netcdf', 'sentinel-3-synergy-vgp-l2-netcdf', 'sentinel-3-synergy-vg1-l2-netcdf', 'esa-worldcover'] for planetary_computer
2024-01-08 09:58:46,011 eodag.core                       [DEBUG   ] (tid=139964798083072) Added product types ['landsat-c2ard-st', 'landsat-c2l3-fsca', 'landsat-c2ard-bt', 'landsat-c2l3-ba', 'landsat-c2ard-sr', 'landsat-c2l3-dswe', 'landsat-c2ard-ta'] for usgs_satapi_aws
2024-01-08 09:58:46,013 eodag.core                       [DEBUG   ] (tid=139964798083072) Out-of-date product types index removed from /home/msordi/.config/eodag/.index
2024-01-08 09:58:46,013 eodag.core                       [DEBUG   ] (tid=139964798083072) Creating product types index in /home/msordi/.config/eodag/.index
2024-01-08 09:58:46,122 eodag.config                     [DEBUG   ] (tid=139964798083072) Loading configuration from /home/msordi/.local/lib/python3.10/site-packages/eodag/resources/providers.yml
2024-01-08 09:58:46,237 eodag.search.qssearch            [INFO    ] (tid=139964798083072) Fetching product types: https://hydroweb.next.theia-land.fr/api/v1/rs-catalog/stac/search/../collections
2024-01-08 09:58:47,801 eodag.core                       [DEBUG   ] (tid=139964798083072) Added product types ['SWOT_L2_HR_LAKESP_PRIOR_SAMPLE_V1_2', 'SWOT_L2_HR_RIVERSP_NODE_SAMPLE_V1_2', 'SWOT_L2_HR_RASTER_100M_SAMPLE_V1_2', 'FLOODDAM_CERFACS_FLOOD_EXTENT', 'FLOODDAM_QUANTCUBE', 'SWOT_L2_HR_LAKESP_OBS', 'SWOT_L2_HR_RASTER_250M_SAMPLE_V1_2', 'SWOT_L2_HR_RIVERSP_NODE', 'SWOT_L2_HR_LAKESP_UNASSIGNED', 'FLOODDAM_CERFACS_VELOCITY', 'SWOT_PRIOR_RIVER_DATABASE', 'FLOODDAM_FLOODML_FLOOD_MAPPING', 'SWOT_L2_HR_RASTER_100M', 'HYDROWEB_RIVERS', 'SWOT_L1B_HR_SLC_SAMPLE_V1_2', 'SW_L3_S2_YEARLY', 'SWOT_L1B_HR_SLC', 'LIS_SNT_YEARLY', 'SWOT_L2_HR_PIXC_SAMPLE_V1_2', 'SWOT_L2_HR_LAKESP_OBS_SAMPLE_V1_2', 'SW_L2_S2_SINGLE', 'SWOT_L2_HR_RIVERSP_REACH', 'SWOT_L2_HR_RIVERSP_REACH_SAMPLE_V1_2', 'SWOT_L2_HR_LAKESP_UNASSIGNED_SAMPLE_V1_2', 'SWOT_L2_HR_RASTER_250M', 'WQ_L2B_S2', 'HYDROWEB_LAKES', 'FLOODDAM_CERFACS_WATER_DEPTH_RASTER', 'SWOT_PRIOR_LAKE_DATABASE', 'SWOT_L2_HR_PIXCVEC', 'SWOT_L2_HR_PIXCVEC_SAMPLE_V1_2', 'SW_L3_S2_MONTHLY', 'SWOT_L2_HR_PIXC', 'SWOT_L2_HR_LAKESP_PRIOR', 'GRS_L2A_S2', 'FLOODDAM_CERFACS_WATER_DEPTH_VECTOR', 'LIS_FSC_PREOP'] for hydroweb_next
2024-01-08 09:58:47,803 eodag.core                       [DEBUG   ] (tid=139964798083072) Out-of-date product types index removed from /home/msordi/.config/eodag/.index
2024-01-08 09:58:47,803 eodag.core                       [DEBUG   ] (tid=139964798083072) Creating product types index in /home/msordi/.config/eodag/.index
2024-01-08 09:58:47,925 eodag.core                       [WARNING ] (tid=139964798083072) Product type 'HYDROWEB_RIVERS' is not available with provider 'peps'. Searching it on provider 'hydroweb_next' instead.
2024-01-08 09:58:47,925 eodag.core                       [DEBUG   ] (tid=139964798083072) Searching for all the products with provider hydroweb_next and a maximum of 10000 items per page.
2024-01-08 09:58:47,925 eodag.core                       [INFO    ] (tid=139964798083072) Iterate search over multiple pages: page #1
2024-01-08 09:58:47,925 eodag.search.base                [DEBUG   ] (tid=139964798083072) Mapping eodag product type to provider product type
2024-01-08 09:58:47,925 eodag.search.base                [DEBUG   ] (tid=139964798083072) Getting provider product type definition parameters for HYDROWEB_RIVERS
2024-01-08 09:58:47,925 eodag.search.qssearch            [DEBUG   ] (tid=139964798083072) Building the query string that will be used for search
2024-01-08 09:58:47,925 eodag.product.metadata_mapping   [DEBUG   ] (tid=139964798083072) Retrieving queryable metadata from metadata_mapping
2024-01-08 09:58:47,925 eodag.search.qssearch            [INFO    ] (tid=139964798083072) Sending search request: https://hydroweb.next.theia-land.fr/api/v1/rs-catalog/stac/search
2024-01-08 09:58:47,925 eodag.search.qssearch            [DEBUG   ] (tid=139964798083072) Query parameters: {'collections': ['HYDROWEB_RIVERS'], 'limit': 10000, 'page': 1}
2024-01-08 09:58:53,192 eodag.search.qssearch            [ERROR   ] (tid=139964798083072) Skipping error while searching for hydroweb_next StacSearch instance:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 446, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 448, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='hydroweb.next.theia-land.fr', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/msordi/.local/lib/python3.10/site-packages/eodag/plugins/search/qssearch.py", line 1107, in _request
    response = requests.post(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='hydroweb.next.theia-land.fr', port=443): Read timed out. (read timeout=5)
2024-01-08 09:58:53,194 eodag.core                       [INFO    ] (tid=139964798083072) No result from provider 'hydroweb_next' due to an error during search.
2024-01-08 09:58:53,194 eodag.core                       [WARNING ] (tid=139964798083072) error at retrieval of data from hydroweb_next, for params: {'productType': 'HYDROWEB_RIVERS', 'geometry': None, 'page': 1, 'items_per_page': 10000}
2024-01-08 09:58:53,194 eodag.core                       [ERROR   ] (tid=139964798083072) No result could be obtained from any available provider
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 446, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 448, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='hydroweb.next.theia-land.fr', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/msordi/.local/lib/python3.10/site-packages/eodag/plugins/search/qssearch.py", line 1107, in _request
    response = requests.post(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='hydroweb.next.theia-land.fr', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/msordi/git/git-hysope2/deployment/misc/stac/download_Theia_Hydroweb_Altimetry_River_Water_Level.py", line 64, in <module>
    search_results = dag.search_all(
  File "/home/msordi/.local/lib/python3.10/site-packages/eodag/api/core.py", line 1238, in search_all
    for page_results in self.search_iter_page_plugin(
  File "/home/msordi/.local/lib/python3.10/site-packages/eodag/api/core.py", line 1070, in search_iter_page_plugin
    products, _ = self._do_search(
  File "/home/msordi/.local/lib/python3.10/site-packages/eodag/api/core.py", line 1540, in _do_search
    res, nb_res = search_plugin.query(count=count, auth=auth_plugin, **kwargs)
  File "/home/msordi/.local/lib/python3.10/site-packages/eodag/plugins/search/qssearch.py", line 1028, in query
    provider_results = self.do_search(items_per_page=items_per_page, **kwargs)
  File "/home/msordi/.local/lib/python3.10/site-packages/eodag/plugins/search/qssearch.py", line 557, in do_search
    response = self._request(
  File "/home/msordi/.local/lib/python3.10/site-packages/eodag/plugins/search/qssearch.py", line 1142, in _request
    raise RequestError(str(err))
eodag.utils.exceptions.RequestError: HTTPSConnectionPool(host='hydroweb.next.theia-land.fr', port=443): Read timed out. (read timeout=5)
``

**Environment:**
 - Python version: `python --version` : 3.10.12
 - EODAG version: `eodag version` : 2.11.0

**Additional context**
Add any other context about the bug here.

**Comment by sbrunato** [comment]
hello @msordi , it seems that the default 5s search timeout is not enough to search for 1000 items in your configuration.
You can try to increase its value in your eodag configuration or with an environment variable:
```py
os.environ["EODAG__HYDROWEB_NEXT__SEARCH__TIMEOUT"] = "10"

dag = EODataAccessGateway()

```
